version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
      - "5555:5555"

    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:4000
