version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
      - "5555:5555" # Optional: Prisma Studio
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    command: npm run start

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:4000
    depends_on:
      - backend
